// ASCII art data, copied verbatim from the standalone prototype.
// FACE = the glyph self-portrait (avatar). IAN = the block-letter wordmark.

export const FACE: string[] = [
  "                                         vvnxx  c",
  "                           vv        xznv   v xzU nzvzxn",
  "                      vnvx        vvnxn   xz  x nX Y0XYwz",
  "                           cnn         cvnxxvvn  vYUx c n mn",
  "                 Z   n  n     X  x           XncQXz zzc    Z",
  "                c      z      Y  0       z cxnxzXXX v v   v   nk",
  "              n      c z  xnc v  OU   nn nxUc   vvc      c   zko x",
  "            n  c     X v   Xz  v   n    v  z vn        c   xzOwO h",
  "            v   z    cv c           cc    nQUYv   cvJx v   h*cv  Q",
  "           Q     c    c   c           nQJZxcnJQOm#*oMovzOU YQ   J",
  "           Y    cc                   nvXQwmpW%BBBB%%WWXYZ0v     0",
  "              c                     vXwWWoWo***M8B%M#*z",
  "                            cXQpddkhkMkmOOkd#M&&&M&M*ohOv      Z",
  "                        c czOo#W&W&8opmdko&BBBBBB%8%8*###hn    Y",
  "                   nQv vcUho00#M8%%8#W&pW%B%&8#MkmXUmmo**M*",
  "                   dpv c  cc cxJZkW#U*M UYx      0dkdk*8#Wk   X Jz",
  "                   oon             v U*On v     XOZQXzp*M&#v  phdJO",
  "                   khz    x   nc    vh%B#mY  Qx  cc v0kWM#MY o#&v",
  "               n Y hn     XvcnQUc   JW8%W*On  c xohZh%BB&W##  m&Bd",
  "               dx  Wn nxv   xv      ZM8B&#WWhXzOpW8BBBBB&&*& UJXk8",
  "               Jc  QnvmohdmZwZJx     #88MW&BB%88WM8BBBBB&&*OOBmcwO",
  "                    YcJhWMM*kO0X    O#M**#&%BBBBB%BBB8B8&Wd UUwMm",
  "                  X Zc zJpoMwZOn  cXoM88&*ok8B%BBBBB8MM*MhYwpkB%",
  "                 Uz nUc  YmwZZv  QXJo%BBBMBMw8BB%B%8M&WMo0Z0BB&J",
  "                 xzx Qncc nQzn   Y  xZkZOJwho%%%B&%&M*#kUdh xwz",
  "                     cOcc  vYcccv    n h#kOoBBB%B%8WhWkp*Wpc",
  "                      Zx vvcQQQJUvcn*BQzBBBBB%88#WW*#MwW8kc",
  "                      cQn xcY    QJYwhpOdpk#MWpk*##hM*WMhY",
  "                       vp cU           nxxxvvXOxJ#&*hphwX",
  "                        XX J  nvcv cQkhQdMhZ0MB&dwhdwoQx",
  "                         vn c cc XXxxzYzzmdW%&khdmmo#U",
  "                           cc      xUv zXQk**kd*o*p*z",
  "                               xzYUxUQpW&WM8%8%B8dcv",
  "                                vJ0OwwM#W%%B%88WZ",
  "                                    vwOvxmddkd0",
];

export const IAN: string[] = [
  "██╗ █████╗ ███╗   ██╗",
  "██║██╔══██╗████╗  ██║",
  "██║███████║██╔██╗ ██║",
  "██║██╔══██║██║╚██╗██║",
  "██║██║  ██║██║ ╚████║",
  "╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝",
];
